version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lorenzodonini"

  - package-ecosystem: "docker"
    directory: "/example/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lorenzodonini"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lorenzodonini"