all: true
dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/lorenzodonini/ocpp-go/ocpp1.6:
    config:
      dir: ocpp1.6_test/mocks
    interfaces:
      CentralSystem: {}
      ChargePoint: {}
      ChargePointConnection: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/certificates:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockCertificates{{.InterfaceName}}
      filename: mock_certificates_{{.InterfaceName|snakecase}}.go
    interfaces:
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/core:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockCore{{.InterfaceName}}
      filename: mock_core_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/extendedtriggermessage:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockExtendedTriggerMessage{{.InterfaceName}}
      filename: mock_extended_trigger_message_{{.InterfaceName|snakecase}}.go
    interfaces:
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/firmware:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockFirmware{{.InterfaceName}}
      filename: mock_firmware_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/localauth:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockLocalAuthList{{.InterfaceName}}
      filename: mock_local_auth_list_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/logging:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockLog{{.InterfaceName}}
      filename: mock_logging_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/remotetrigger:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockRemoteTrigger{{.InterfaceName}}
      filename: mock_remote_trigger_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/reservation:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockReservation{{.InterfaceName}}
      filename: mock_reservation_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/securefirmware:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockSecureFirmware{{.InterfaceName}}
      filename: mock_secure_firmware_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/security:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockSecurity{{.InterfaceName}}
      filename: mock_security_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocpp1.6/smartcharging:
    config:
      dir: ocpp1.6_test/mocks
      structname: MockSmartCharging{{.InterfaceName}}
      filename: mock_smart_charging_{{.InterfaceName|snakecase}}.go
    interfaces:
      CentralSystemHandler: {}
      ChargePointHandler: {}
  github.com/lorenzodonini/ocpp-go/ocppj:
    interfaces:
      RequestQueue: {}
      ServerQueueMap: {}
  github.com/lorenzodonini/ocpp-go/ws:
    interfaces:
      Channel: {}
      Client: {}
      Server: {}
