version: "3.9"
services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.11.0
    hostname: toxiproxy

  unit_test:
    # The tests might require permissions to write to coverage out files.
    # If you encounter issues with permissions, you can try running the container as root.
    user: root
    image: cimg/go:1.24.3
    working_dir: /etc/ocpp-go
    volumes:
      - .:/etc/ocpp-go:rw
    command:
      - /bin/bash
      - -c
      - |
        go test -race -v -covermode=atomic -coverprofile=coverage.out ./ocppj
        go test -race -v -covermode=atomic -coverprofile=ocpp16.out -coverpkg=github.com/lorenzodonini/ocpp-go/ocpp1.6/... github.com/lorenzodonini/ocpp-go/ocpp1.6_test
        go test -race -v -covermode=atomic -coverprofile=ocpp201.out -coverpkg=github.com/lorenzodonini/ocpp-go/ocpp2.0.1/... github.com/lorenzodonini/ocpp-go/ocpp2.0.1_test
        sed '1d;$d' ocpp16.out >> coverage.out
        sed '1d;$d' ocpp201.out >> coverage.out

  integration_test:
    image: cimg/go:1.24.3
    # The tests might require permissions to write to coverage out files.
    # If you encounter issues with permissions, you can try running the container as root.
    user: root
    working_dir: /etc/ocpp-go
    environment:
      - TOXIPROXY_HOST=toxiproxy
      - TOXIPROXY_PORT=8474
      - PROXY_OCPP_LISTENER=toxiproxy:8886
      - PROXY_OCPP_UPSTREAM=integration_test:8887
    depends_on:
      - toxiproxy
    command:
      - /bin/bash
      - -c
      - go test -race ./ws -v -covermode=atomic -coverprofile=integration_coverage.out
    volumes:
      - .:/etc/ocpp-go:rw