// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	ws "github.com/lorenzodonini/ocpp-go/ws"
	mock "github.com/stretchr/testify/mock"
)

// MockDisconnectedHandler is an autogenerated mock type for the DisconnectedHandler type
type MockDisconnectedHandler struct {
	mock.Mock
}

type MockDisconnectedHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisconnectedHandler) EXPECT() *MockDisconnectedHandler_Expecter {
	return &MockDisconnectedHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: c, err
func (_m *MockDisconnectedHandler) Execute(c ws.Channel, err error) {
	_m.Called(c, err)
}

// MockDisconnectedHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDisconnectedHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - c ws.Channel
//   - err error
func (_e *MockDisconnectedHandler_Expecter) Execute(c interface{}, err interface{}) *MockDisconnectedHandler_Execute_Call {
	return &MockDisconnectedHandler_Execute_Call{Call: _e.mock.On("Execute", c, err)}
}

func (_c *MockDisconnectedHandler_Execute_Call) Run(run func(c ws.Channel, err error)) *MockDisconnectedHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ws.Channel), args[1].(error))
	})
	return _c
}

func (_c *MockDisconnectedHandler_Execute_Call) Return() *MockDisconnectedHandler_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDisconnectedHandler_Execute_Call) RunAndReturn(run func(ws.Channel, error)) *MockDisconnectedHandler_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockDisconnectedHandler creates a new instance of MockDisconnectedHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisconnectedHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisconnectedHandler {
	mock := &MockDisconnectedHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
