// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockServerOpt is an autogenerated mock type for the ServerOpt type
type MockServerOpt struct {
	mock.Mock
}

type MockServerOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerOpt) EXPECT() *MockServerOpt_Expecter {
	return &MockServerOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: s
func (_m *MockServerOpt) Execute(s *ws.server) {
	_m.Called(s)
}

// MockServerOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockServerOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - s *ws.server
func (_e *MockServerOpt_Expecter) Execute(s interface{}) *MockServerOpt_Execute_Call {
	return &MockServerOpt_Execute_Call{Call: _e.mock.On("Execute", s)}
}

func (_c *MockServerOpt_Execute_Call) Run(run func(s *ws.server)) *MockServerOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ws.server))
	})
	return _c
}

func (_c *MockServerOpt_Execute_Call) Return() *MockServerOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerOpt_Execute_Call) RunAndReturn(run func(*ws.server)) *MockServerOpt_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockServerOpt creates a new instance of MockServerOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerOpt {
	mock := &MockServerOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
