// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ws "github.com/lorenzodonini/ocpp-go/ws"
	mock "github.com/stretchr/testify/mock"
)

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

type MockErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandler) EXPECT() *MockErrorHandler_Expecter {
	return &MockErrorHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: c, err
func (_m *MockErrorHandler) Execute(c ws.Channel, err error) {
	_m.Called(c, err)
}

// MockErrorHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockErrorHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - c ws.Channel
//   - err error
func (_e *MockErrorHandler_Expecter) Execute(c interface{}, err interface{}) *MockErrorHandler_Execute_Call {
	return &MockErrorHandler_Execute_Call{Call: _e.mock.On("Execute", c, err)}
}

func (_c *MockErrorHandler_Execute_Call) Run(run func(c ws.Channel, err error)) *MockErrorHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ws.Channel), args[1].(error))
	})
	return _c
}

func (_c *MockErrorHandler_Execute_Call) Return() *MockErrorHandler_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Execute_Call) RunAndReturn(run func(ws.Channel, error)) *MockErrorHandler_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorHandler creates a new instance of MockErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandler {
	mock := &MockErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
