// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ws "github.com/lorenzodonini/ocpp-go/ws"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddOption provides a mock function with given fields: option
func (_m *MockClient) AddOption(option interface{}) {
	_m.Called(option)
}

// MockClient_AddOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOption'
type MockClient_AddOption_Call struct {
	*mock.Call
}

// AddOption is a helper method to define mock.On call
//   - option interface{}
func (_e *MockClient_Expecter) AddOption(option interface{}) *MockClient_AddOption_Call {
	return &MockClient_AddOption_Call{Call: _e.mock.On("AddOption", option)}
}

func (_c *MockClient_AddOption_Call) Run(run func(option interface{})) *MockClient_AddOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockClient_AddOption_Call) Return() *MockClient_AddOption_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_AddOption_Call) RunAndReturn(run func(interface{})) *MockClient_AddOption_Call {
	_c.Run(run)
	return _c
}

// Errors provides a mock function with no fields
func (_m *MockClient) Errors() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// MockClient_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockClient_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *MockClient_Expecter) Errors() *MockClient_Errors_Call {
	return &MockClient_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *MockClient_Errors_Call) Run(run func()) *MockClient_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Errors_Call) Return(_a0 <-chan error) *MockClient_Errors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Errors_Call) RunAndReturn(run func() <-chan error) *MockClient_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *MockClient) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockClient_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockClient_Expecter) IsConnected() *MockClient_IsConnected_Call {
	return &MockClient_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockClient_IsConnected_Call) Run(run func()) *MockClient_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_IsConnected_Call) Return(_a0 bool) *MockClient_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_IsConnected_Call) RunAndReturn(run func() bool) *MockClient_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// SetBasicAuth provides a mock function with given fields: username, password
func (_m *MockClient) SetBasicAuth(username string, password string) {
	_m.Called(username, password)
}

// MockClient_SetBasicAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBasicAuth'
type MockClient_SetBasicAuth_Call struct {
	*mock.Call
}

// SetBasicAuth is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockClient_Expecter) SetBasicAuth(username interface{}, password interface{}) *MockClient_SetBasicAuth_Call {
	return &MockClient_SetBasicAuth_Call{Call: _e.mock.On("SetBasicAuth", username, password)}
}

func (_c *MockClient_SetBasicAuth_Call) Run(run func(username string, password string)) *MockClient_SetBasicAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_SetBasicAuth_Call) Return() *MockClient_SetBasicAuth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetBasicAuth_Call) RunAndReturn(run func(string, string)) *MockClient_SetBasicAuth_Call {
	_c.Run(run)
	return _c
}

// SetDisconnectedHandler provides a mock function with given fields: handler
func (_m *MockClient) SetDisconnectedHandler(handler func(error)) {
	_m.Called(handler)
}

// MockClient_SetDisconnectedHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDisconnectedHandler'
type MockClient_SetDisconnectedHandler_Call struct {
	*mock.Call
}

// SetDisconnectedHandler is a helper method to define mock.On call
//   - handler func(error)
func (_e *MockClient_Expecter) SetDisconnectedHandler(handler interface{}) *MockClient_SetDisconnectedHandler_Call {
	return &MockClient_SetDisconnectedHandler_Call{Call: _e.mock.On("SetDisconnectedHandler", handler)}
}

func (_c *MockClient_SetDisconnectedHandler_Call) Run(run func(handler func(error))) *MockClient_SetDisconnectedHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(error)))
	})
	return _c
}

func (_c *MockClient_SetDisconnectedHandler_Call) Return() *MockClient_SetDisconnectedHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetDisconnectedHandler_Call) RunAndReturn(run func(func(error))) *MockClient_SetDisconnectedHandler_Call {
	_c.Run(run)
	return _c
}

// SetHeaderValue provides a mock function with given fields: key, value
func (_m *MockClient) SetHeaderValue(key string, value string) {
	_m.Called(key, value)
}

// MockClient_SetHeaderValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaderValue'
type MockClient_SetHeaderValue_Call struct {
	*mock.Call
}

// SetHeaderValue is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockClient_Expecter) SetHeaderValue(key interface{}, value interface{}) *MockClient_SetHeaderValue_Call {
	return &MockClient_SetHeaderValue_Call{Call: _e.mock.On("SetHeaderValue", key, value)}
}

func (_c *MockClient_SetHeaderValue_Call) Run(run func(key string, value string)) *MockClient_SetHeaderValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_SetHeaderValue_Call) Return() *MockClient_SetHeaderValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetHeaderValue_Call) RunAndReturn(run func(string, string)) *MockClient_SetHeaderValue_Call {
	_c.Run(run)
	return _c
}

// SetMessageHandler provides a mock function with given fields: handler
func (_m *MockClient) SetMessageHandler(handler func([]byte) error) {
	_m.Called(handler)
}

// MockClient_SetMessageHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessageHandler'
type MockClient_SetMessageHandler_Call struct {
	*mock.Call
}

// SetMessageHandler is a helper method to define mock.On call
//   - handler func([]byte) error
func (_e *MockClient_Expecter) SetMessageHandler(handler interface{}) *MockClient_SetMessageHandler_Call {
	return &MockClient_SetMessageHandler_Call{Call: _e.mock.On("SetMessageHandler", handler)}
}

func (_c *MockClient_SetMessageHandler_Call) Run(run func(handler func([]byte) error)) *MockClient_SetMessageHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func([]byte) error))
	})
	return _c
}

func (_c *MockClient_SetMessageHandler_Call) Return() *MockClient_SetMessageHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetMessageHandler_Call) RunAndReturn(run func(func([]byte) error)) *MockClient_SetMessageHandler_Call {
	_c.Run(run)
	return _c
}

// SetReconnectedHandler provides a mock function with given fields: handler
func (_m *MockClient) SetReconnectedHandler(handler func()) {
	_m.Called(handler)
}

// MockClient_SetReconnectedHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReconnectedHandler'
type MockClient_SetReconnectedHandler_Call struct {
	*mock.Call
}

// SetReconnectedHandler is a helper method to define mock.On call
//   - handler func()
func (_e *MockClient_Expecter) SetReconnectedHandler(handler interface{}) *MockClient_SetReconnectedHandler_Call {
	return &MockClient_SetReconnectedHandler_Call{Call: _e.mock.On("SetReconnectedHandler", handler)}
}

func (_c *MockClient_SetReconnectedHandler_Call) Run(run func(handler func())) *MockClient_SetReconnectedHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockClient_SetReconnectedHandler_Call) Return() *MockClient_SetReconnectedHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetReconnectedHandler_Call) RunAndReturn(run func(func())) *MockClient_SetReconnectedHandler_Call {
	_c.Run(run)
	return _c
}

// SetRequestedSubProtocol provides a mock function with given fields: subProto
func (_m *MockClient) SetRequestedSubProtocol(subProto string) {
	_m.Called(subProto)
}

// MockClient_SetRequestedSubProtocol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRequestedSubProtocol'
type MockClient_SetRequestedSubProtocol_Call struct {
	*mock.Call
}

// SetRequestedSubProtocol is a helper method to define mock.On call
//   - subProto string
func (_e *MockClient_Expecter) SetRequestedSubProtocol(subProto interface{}) *MockClient_SetRequestedSubProtocol_Call {
	return &MockClient_SetRequestedSubProtocol_Call{Call: _e.mock.On("SetRequestedSubProtocol", subProto)}
}

func (_c *MockClient_SetRequestedSubProtocol_Call) Run(run func(subProto string)) *MockClient_SetRequestedSubProtocol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_SetRequestedSubProtocol_Call) Return() *MockClient_SetRequestedSubProtocol_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetRequestedSubProtocol_Call) RunAndReturn(run func(string)) *MockClient_SetRequestedSubProtocol_Call {
	_c.Run(run)
	return _c
}

// SetTimeoutConfig provides a mock function with given fields: config
func (_m *MockClient) SetTimeoutConfig(config ws.ClientTimeoutConfig) {
	_m.Called(config)
}

// MockClient_SetTimeoutConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeoutConfig'
type MockClient_SetTimeoutConfig_Call struct {
	*mock.Call
}

// SetTimeoutConfig is a helper method to define mock.On call
//   - config ws.ClientTimeoutConfig
func (_e *MockClient_Expecter) SetTimeoutConfig(config interface{}) *MockClient_SetTimeoutConfig_Call {
	return &MockClient_SetTimeoutConfig_Call{Call: _e.mock.On("SetTimeoutConfig", config)}
}

func (_c *MockClient_SetTimeoutConfig_Call) Run(run func(config ws.ClientTimeoutConfig)) *MockClient_SetTimeoutConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ws.ClientTimeoutConfig))
	})
	return _c
}

func (_c *MockClient_SetTimeoutConfig_Call) Return() *MockClient_SetTimeoutConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetTimeoutConfig_Call) RunAndReturn(run func(ws.ClientTimeoutConfig)) *MockClient_SetTimeoutConfig_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: url
func (_m *MockClient) Start(url string) error {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - url string
func (_e *MockClient_Expecter) Start(url interface{}) *MockClient_Start_Call {
	return &MockClient_Start_Call{Call: _e.mock.On("Start", url)}
}

func (_c *MockClient_Start_Call) Run(run func(url string)) *MockClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Start_Call) Return(_a0 error) *MockClient_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Start_Call) RunAndReturn(run func(string) error) *MockClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartWithRetries provides a mock function with given fields: url
func (_m *MockClient) StartWithRetries(url string) {
	_m.Called(url)
}

// MockClient_StartWithRetries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWithRetries'
type MockClient_StartWithRetries_Call struct {
	*mock.Call
}

// StartWithRetries is a helper method to define mock.On call
//   - url string
func (_e *MockClient_Expecter) StartWithRetries(url interface{}) *MockClient_StartWithRetries_Call {
	return &MockClient_StartWithRetries_Call{Call: _e.mock.On("StartWithRetries", url)}
}

func (_c *MockClient_StartWithRetries_Call) Run(run func(url string)) *MockClient_StartWithRetries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_StartWithRetries_Call) Return() *MockClient_StartWithRetries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_StartWithRetries_Call) RunAndReturn(run func(string)) *MockClient_StartWithRetries_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockClient) Stop() {
	_m.Called()
}

// MockClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockClient_Expecter) Stop() *MockClient_Stop_Call {
	return &MockClient_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockClient_Stop_Call) Run(run func()) *MockClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Stop_Call) Return() *MockClient_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Stop_Call) RunAndReturn(run func()) *MockClient_Stop_Call {
	_c.Run(run)
	return _c
}

// Write provides a mock function with given fields: data
func (_m *MockClient) Write(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockClient_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - data []byte
func (_e *MockClient_Expecter) Write(data interface{}) *MockClient_Write_Call {
	return &MockClient_Write_Call{Call: _e.mock.On("Write", data)}
}

func (_c *MockClient_Write_Call) Run(run func(data []byte)) *MockClient_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockClient_Write_Call) Return(_a0 error) *MockClient_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Write_Call) RunAndReturn(run func([]byte) error) *MockClient_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
