name: Autogenerate
on:
  # Note: When testing with nektos/act, the workflow_dispatch does not work as of version 0.2.63
  workflow_dispatch:

  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  mockery:
    name: Generate mocks
    runs-on: ubuntu-latest

    # Permissions are needed to push the changes back to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Install Mockery
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific tag
          repo: vektra/mockery
          tag: v2.53.3

      - name: Generate mocks
        run: mockery
      - name: Cache generated mocks
        uses: actions/cache@v4
        with:
          path: |
            ocpp1.6_test/mocks/
            ocpp2.0.1_test/mocks/
            ocppj/mocks/
            ws/mocks/
          key: ${{ runner.os }}-mocks-${{ github.sha }}
