name: Autogenerate
on:
  # Note: When testing with nektos/act, the workflow_dispatch does not work as of version 0.2.63
  workflow_dispatch:

  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  mockery:
    name: Generate mocks
    runs-on: ubuntu-latest

    # Permissions are needed to push the changes back to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Install Mockery
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific tag
          repo: vektra/mockery
          tag: v2.51.0

      - name: Generate mocks
        run: mockery

        # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        #with:
        #  commit_message: [ Autogen ] Generated mocks
        #  # Mockery can generate new files, so we need to add them to the commit as well
        #  add_options: '$(git ls-files -o --exclude-standard)'
        #  file_pattern: '*.go' # Only commit changes to Go files
        #  # Only create a branch when the workflow is triggered manually
        #  create_branch: ${{ github.event_name == 'workflow_dispatch' }}
