name: "Lint"

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
    branches:
      - master

jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.16"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest