// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLocalAuthListCentralSystemHandler is an autogenerated mock type for the CentralSystemHandler type
type MockLocalAuthListCentralSystemHandler struct {
	mock.Mock
}

type MockLocalAuthListCentralSystemHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocalAuthListCentralSystemHandler) EXPECT() *MockLocalAuthListCentralSystemHandler_Expecter {
	return &MockLocalAuthListCentralSystemHandler_Expecter{mock: &_m.Mock}
}

// NewMockLocalAuthListCentralSystemHandler creates a new instance of MockLocalAuthListCentralSystemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocalAuthListCentralSystemHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocalAuthListCentralSystemHandler {
	mock := &MockLocalAuthListCentralSystemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
