// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSmartChargingCentralSystemHandler is an autogenerated mock type for the CentralSystemHandler type
type MockSmartChargingCentralSystemHandler struct {
	mock.Mock
}

type MockSmartChargingCentralSystemHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSmartChargingCentralSystemHandler) EXPECT() *MockSmartChargingCentralSystemHandler_Expecter {
	return &MockSmartChargingCentralSystemHandler_Expecter{mock: &_m.Mock}
}

// NewMockSmartChargingCentralSystemHandler creates a new instance of MockSmartChargingCentralSystemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSmartChargingCentralSystemHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSmartChargingCentralSystemHandler {
	mock := &MockSmartChargingCentralSystemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
