// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRemoteTriggerCentralSystemHandler is an autogenerated mock type for the CentralSystemHandler type
type MockRemoteTriggerCentralSystemHandler struct {
	mock.Mock
}

type MockRemoteTriggerCentralSystemHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteTriggerCentralSystemHandler) EXPECT() *MockRemoteTriggerCentralSystemHandler_Expecter {
	return &MockRemoteTriggerCentralSystemHandler_Expecter{mock: &_m.Mock}
}

// NewMockRemoteTriggerCentralSystemHandler creates a new instance of MockRemoteTriggerCentralSystemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteTriggerCentralSystemHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteTriggerCentralSystemHandler {
	mock := &MockRemoteTriggerCentralSystemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
